# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fintoc < Formula
  desc "Fintoc CLI for interacting with the Fintoc API"
  homepage "https://fintoc.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fintoc-com/fintoc-cli/releases/download/v0.1.0/fintoc_0.1.0_darwin_amd64.tar.gz"
      sha256 "efa4fc599bee89d72ab9087ecbf61dbaa9b79b32b8350ed3c0b0c875accdff50"

      define_method(:install) do
        bin.install "fintoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fintoc-com/fintoc-cli/releases/download/v0.1.0/fintoc_0.1.0_darwin_arm64.tar.gz"
      sha256 "8a65a80ad0d0d9e6af3ad22a8917af5ccdb9938f20c39775dd111450b627caa3"

      define_method(:install) do
        bin.install "fintoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fintoc-com/fintoc-cli/releases/download/v0.1.0/fintoc_0.1.0_linux_amd64.tar.gz"
      sha256 "9c4387b7e1987b0eda1614263733af135f8fc41beb21cb6e54137d96d90e6ae5"
      define_method(:install) do
        bin.install "fintoc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fintoc-com/fintoc-cli/releases/download/v0.1.0/fintoc_0.1.0_linux_arm64.tar.gz"
      sha256 "390fccf4a76fd01b4f6563016ea86f58fde7e21ee3c273fd699248df1fa94c07"
      define_method(:install) do
        bin.install "fintoc"
      end
    end
  end

  test do
    system "#{bin}/fintoc", "version"
  end
end
